check for top level pair directory and fail if it is not setup correctly.. etc

diff --git a/disable_pair b/disable_pair
--- a/disable_pair
+++ b/disable_pair
@@ -9,7 +9,13 @@ if [ "$1" = "" ] ; then
   exit 0
 fi
 
+die() {
+  echo "$*"
+  exit 1
+}
+
 #PAIRDIR=/tmp/${USER}.pair
 PAIRDIR=/tmp/pair-cobbler
-cd $PAIDIR
+
+cd $PAIRDIR || die "$PAIRDIR not found/accessible"
 rm "$1".pairssh
